### ISSUE TITLE
Duskcord and WitcherCord have issues since the newest UI update

### ISSUE THREAD

**Issue by thanatossystem** [jadeonking/Witcher-3-Theme-for-Discord#4]
The text and voice chat tab have reverted to original discord ones and the settings are all discord default too.

**Comment by jadeonking** [comment]
Hello thanatossytem I am aware of this issue however as of this moment I am not motivated to fix Dusk or Witcher and cannot tell you at this moment when either will be fixed :(

**Comment by thanatossystem** [comment]
Aw, damn. I really like the Duskcord style and would use it again when/if it gets fixed.
Until then, have a good one :)

**Comment by jadeonking** [comment]
I went ahead and fixed the channel list and account details as I felt I could at least fix that as it was simple enough I will have it up soon the rest however not sure when I will fix

**Comment by jadeonking** [comment]
I have released a channel, voice, and private fix for now I will leave this open until I either fix all current issues or decide to discontinue my themes

**Comment by thanatossystem** [comment]
Thank you very much for the update! Already installed it again. It'd be sad to see this theme discontinued as it's the only style I can identify with. Keep up the good work! :)
